[package]
name = "mangadex-api"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
uuid = { version = "1.3.3", features = ["serde"] }
reqwest = { version = "0.11.18", features = ["json"] }

[dev-dependencies]
tokio = { version = "1.28.1", features = ["macros"] }
